services:
  server:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/server:/careConnect/apps/server
      - ./packages:/careConnect/packages
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command:
      [
        'nodemon',
        '--legacy-watch',
        '--watch',
        './apps/server/',
        '--ext',
        'ts,tsx',
        '--exec',
        'pnpm',
        'ts-node',
        './apps/server/src/server.ts',
      ]
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/careConnect/apps/web
      - ./packages:/careConnect/packages
    command: ['pnpm', 'dev', '--host']
    expose:
      - '5173'
    environment:
      - NODE_ENV=development

  proxy:
    image: nginx:alpine
    depends_on:
      - server
      - web
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_NAME}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres-data:
